# Generated by Django 4.2.9 on 2025-05-05 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_flightcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='room_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
