# Generated by Django 4.2.9 on 2025-05-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0007_reservation_guests_reservation_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='iata_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
