# Generated by Django 4.2.9 on 2025-05-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0007_userprofile_approval_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hotel_city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hotel_contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hotel_country',
            field=models.CharField(blank=True, default='USA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hotel_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hotel_postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hotel_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hotel_state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
