# Generated by Django 4.2.9 on 2025-05-05 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0008_userprofile_hotel_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hotel_iata_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
