# Generated by Django 4.2.9 on 2025-05-08 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TripPackageCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_unique_id', models.CharField(help_text='A unique ID for the package, e.g., trip-flightid-hotelid', max_length=255)),
                ('total_package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('search_departure_date', models.DateField()),
                ('search_return_date', models.DateField()),
                ('flight_id', models.CharField(blank=True, max_length=255, null=True)),
                ('flight_carrier', models.CharField(blank=True, max_length=255, null=True)),
                ('flight_origin', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_destination', models.CharField(blank=True, max_length=100, null=True)),
                ('flight_departure_datetime', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_return_datetime', models.CharField(blank=True, max_length=50, null=True)),
                ('flight_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hotel_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_location', models.CharField(blank=True, max_length=255, null=True)),
                ('hotel_check_in_date', models.CharField(blank=True, max_length=20, null=True)),
                ('hotel_check_out_date', models.CharField(blank=True, max_length=20, null=True)),
                ('hotel_price_per_night', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('num_nights', models.PositiveIntegerField(blank=True, null=True)),
                ('flight_details_json', models.JSONField(blank=True, null=True)),
                ('hotel_details_json', models.JSONField(blank=True, null=True)),
                ('added_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_package_cart_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip Package Cart Item',
                'verbose_name_plural': 'Trip Package Cart Items',
                'ordering': ['-added_on'],
            },
        ),
    ]
